theme: jekyll-theme-architect
title: David Boster
email: david@boster.us
description: Dream big, just don't scare the hell out of everyone ğŸ™‚
twitter_username: davidboster
github_username: daveboster


paginate: 6
paginate_path: "/thoughts/page:num/"
